import "@component/styles/globals.css";
import SideBar from "@component/components/SideBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head />
      <body>
        <div className='flex'>
          <div className='bg-[#202123] max-w-xs h-screen overflow-y-scroll md:min-w-[20rem]'>
            <SideBar />
          </div>
          {/*sidebar*/}
          {/*client provider - notification*/}
          <div className='bg-[#343541] flex-1'>{children}</div>
        </div>
      </body>
    </html>
  );
}
